### ISSUE TITLE
Make get_atlas() GUI

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#101]
In the spirit of get_experiments(), make a get_atlas GUI.  Two pull downs on top, one for username and one for Atlas name.  For a given Atlas name, list the identifications.  

Due to the heterogeneity and complexity of identifications (mz, rt, intensity, fragmentation, ..., etc), Do some basic usability tests with users to present the identifications in a useful way.  Suzie and I would be good people to start with.

**Comment by aitatanit** [comment]
i'll start with compound name, m/z, and rt values. let's see how that works out.

**Comment by benbowen** [comment]
@aitatanit, What's the status of this.  Have you tested since NERSC upgraded?  Please comment and with command to launch and test.

**Comment by aitatanit** [comment]
This was finished long time back. I'll test again and close issue if all is well.

**Comment by aitatanit** [comment]
It works on NERSC...
