### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by aitatanit** [biorack/metatlas#104]
As more users start working with the code we'll have to protect the data that's been processed. We need to implement permission on accessing and using tables as users get created. This is a simple script that is run once a user is granted access to the database but what's tricky is allowing them to work productively without damaging other users' data. The need is not immediate but we should start thinking about this issue.

**Comment by benbowen** [comment]
Also, the mzML files and hdf5 files.  In the OpenMSI project (http://openmsi.nersc.gov) and other projects at NERSC facls (getfacl and setfacl) are added to files and directories to extend the basic linux permissions.

**Comment by aitatanit** [comment]
Good point so that original data is also protected.


--
*Jimmy*
