### ISSUE TITLE
get value from qgrid widget and do something with it

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#110]
I'm trying to utilize the index printed to the screen when clicking on rows in a qgrid widget, but can't figure out how to get at it.  Any pointers?
![image](https://cloud.githubusercontent.com/assets/810953/12803061/95290458-ca9c-11e5-892d-533ccb7080ea.png)

**Comment by benbowen** [comment]
For context, this is what I'm currently doing.  I would prefer it to be clickable.

```
def get_files_for_experiment(experiment_name):
    files = metob.retrieve('LcmsRun',username='*',experiment=experiment_name)
    flist = []
    for f in files:
        flist.append(f.hdf5_file)    
    flist = np.unique(flist)
    return flist

def get_files_from_recent_experiment(num_days):
    if not num_days:
        num_days = 5
    query = 'SELECT DISTINCT experiment,creation_time,username FROM lcmsruns where creation_time >= UNIX_TIMESTAMP(DATE_SUB(CURDATE(), INTERVAL %d DAY))'%num_days
    entries = [e for e in metob.database.query(query)]
    df = pd.DataFrame() 
    counter = 0
    for entry in entries:
        if entry['experiment']:
            df.loc[counter,'experiment'] = entry['experiment']
            df.loc[counter,'username'] = entry['username']
            df.loc[counter, 'utc time'] = datetime.utcfromtimestamp(entry['creation_time'])
            counter = counter + 1

    qgrid.show_grid(df, remote_js=True)
    print "Enter the experiment name here"
    my_experiment = raw_input()
    files =  get_files_for_experiment(my_experiment)
    return files

```

**Comment by blink1073** [comment]
There is a `get_selected_rows()` method on the `Grid`:

https://github.com/quantopian/qgrid/blob/master/qgrid/grid.py#L354

**Comment by benbowen** [comment]
I'm not getting it.  When I look at
https://github.com/quantopian/qgrid/blob/master/qgrid/grid.py#L127

nothing is returned from show_grid(df)

Where do I use the get_selected_rows()?

Its for a dataframe not a list of metatlas objects

**Comment by blink1073** [comment]
show_grid(df) is a convenience function that hides the underlying QGrid, you can use this instead: https://github.com/metabolite-atlas/metatlas/blob/master/metatlas/gui.py#L31

**Comment by benbowen** [comment]
Got it... almost!  I'm getting the index of the selected row(s), but the
they are not in order after sorting and filtering.

**Comment by blink1073** [comment]
In progress: https://github.com/quantopian/qgrid/pull/58

**Comment by blink1073** [comment]
Should be good to go now.

**Comment by benbowen** [comment]
tested and works
