### ISSUE TITLE
run_dirwatch2.sh question

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#115]
I'm getting a lot more "already running" emails than normal from run_dirwatch2.sh.

if [ -e "${PIDFILE}" ] && (ps -u $(whoami) -opid= |
                           grep -P "^\s*$(cat ${PIDFILE})$" &> /dev/null); then
  echo "Already running."
  exit 99
fi

**Comment by blink1073** [comment]
It is in the middle of a big job (469 of 578).
