### ISSUE TITLE
mzintensitypair

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#116]
Can you tell me how to add mzintensitypair?  I'm not getting something
Here is the code:
https://github.com/biorack/metatlas/blob/master/metatlas/metatlas_objects.py#L466

I'm trying variations on this and its not working:
fr = metob.FragmentationReference()
fr.mz_intensities = [(1.,1.),(1.,1.)]

**Comment by benbowen** [comment]
fr = metob.FragmentationReference()
spectrum = []
for i in range(10):
    mzp = metob.MzIntensityPair()
    mzp.mz = 1.
    mzp.intensity = 10.
    spectrum.append(mzp)
fr.mz_intensities = spectrum

**Comment by blink1073** [comment]
Glad you got it sorted.
