### ISSUE TITLE
when filename is passed to h5query.get_data the hdf5 file doesn't get closed

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#119]
Working with @matthewturk at a hackathon and noticed that the files don't get closed within metatlas.  We are working around wtih a "with open() as fid:".

If a user passes in a filename, there is no way to close the files.

**Comment by aitatanit** [comment]
Will this do right before the return statement (line 86)?

    if not isinstance(h5file, tables.File):
        h5file.close()

**Comment by benbowen** [comment]
Seems good to me.  How's it test out?

**Comment by aitatanit** [comment]
I did this instead since the varibale h5file will always end up being a h5table. So I did this and it seems to work when you pass the functions a n h5 file or a table.

AT the top of the function:
```python
is_h5_file = False
    if not isinstance(h5file, tables.File):
        is_h5_file = True
        h5file = tables.open_file(h5file)
```


then before the return statements:
```python 
if is_h5_file:
        h5file.close()
        print('closed file in get_data')
```

I'll clean up & close issue thought a commit
