### ISSUE TITLE
somehow the docs page got wiped out.  please rebuild

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#124]

**Comment by aitatanit** [comment]
I don't this this was ever working. I'll create a doc. Maybe we should link it to the workflow notebook.

**Comment by benbowen** [comment]
There was a docs page that was rendered from teh contents of
/metatlas/docs. Its been there for over a year.

**Comment by aitatanit** [comment]
okay I restored the links (the extension had changed from html to rst) but the one for API is not present in the repo. Check it out and let me know how it looks please.

**Comment by blink1073** [comment]
The link should point to `http://biorack.github.io/metatlas/`

**Comment by blink1073** [comment]
This happened when the organization was renamed.

**Comment by aitatanit** [comment]
Thanks @blink1073. Change made and link is working. closing issue.
