### ISSUE TITLE
atlas.clone(recursive=True) creates a new atlas, but metob.store doesn't save it

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#136]
When I clone an atlas, it looks and acts exactly like a valid atlas, but when I metob.store it, the objects don't get saved.

```
>>> import sys
>>> import getpass
>>> sys.path.insert(0,'/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages' )
>>> from metatlas import metatlas_objects as metob
('Metatlas live in ', '/global/project/projectdirs/metatlas/anaconda/lib/python2.7/site-packages/metatlas')
you're running on edison01 at 128.55.203.21
>>> rt_ref = metob.retrieve('RTReference',unique_id = 'a1c5a5dbec8d47e9b22afd674e43942b', username = '*')
>>> print rt_ref[0].username
bpb
>>> print getpass.getuser()
pasteur
>>> new_rt_ref = rt_ref[0].clone()
>>> new_rt_ref.description = 'here I am trying to store a cloned object'
>>> print len(metob.retrieve('RtReference',username='pasteur'))
1
>>> metob.store(new_rt_ref)
>>> print len(metob.retrieve('RtReference',username='pasteur'))
1
>>>

```

**Comment by benbowen** [comment]
The example above is for an rt_reference, but you see the same result for recursive objects too.  The rt_ref is a simpler example.

**Comment by benbowen** [comment]
>>> type(new_rt_ref)
<class 'metatlas.metatlas_objects.RtReference'>

**Comment by benbowen** [comment]
Just to show that store of freshly minted objects works:

```
>>> hand_made_rt = metob.RtReference()
>>> hand_made_rt.description = 'this is a freshly minted rtreference'
>>> metob.store(hand_made_rt)
>>> print len(metob.retrieve('RtReference',username='pasteur'))
2
```

**Comment by benbowen** [comment]
Another observation is that clone works as expected with store when its same user.  I ran all these commands as bpb

```
rt_ref = metob.retrieve('RTReference',head_id = 'a1c5a5dbec8d47e9b22afd674e43942b', username = '*')
rt_ref
```

Out[80]:
[{'creation_time': '2016-06-18T01:31:49',
  'description': u'No description',
  'enabled': True,
  'head_id': u'a1c5a5dbec8d47e9b22afd674e43942b',
  'last_modified': '2016-06-23T00:57:12',
  'lcms_run': None,
  'name': u'Untitled',
  'prev_uid': u'54bbc299cd464ab4895249371cd79e1a',
  'ref_type': u'',
  'rt_max': 7.06,
  'rt_min': 6.39708032852564,
  'rt_peak': 6.96,
  'rt_units': 'min',
  'unique_id': u'a1c5a5dbec8d47e9b22afd674e43942b',
  'username': u'bpb'}]
In [83]:


```
cloned_ref = rt_ref[0].clone()
cloned_ref.description = 'this is a cloned ref'
print cloned_ref
metob.store(cloned_ref)

```

{'creation_time': '2016-06-23T19:24:46',
 'description': u'this is a cloned ref',
 'enabled': True,
 'head_id': u'a1c5a5dbec8d47e9b22afd674e43942b',
 'last_modified': '2016-06-23T19:24:46',
 'lcms_run': None,
 'name': u'Untitled',
 'prev_uid': u'a1c5a5dbec8d47e9b22afd674e43942b',
 'ref_type': u'',
 'rt_max': 7.06,
 'rt_min': 6.39708032852564,
 'rt_peak': 6.96,
 'rt_units': 'min',
 'unique_id': u'0224928385b6426ab236fc8492137a94',
 'username': u'bpb'}
In [85]:


```
retrieved_ref = metob.retrieve('RtReference',unique_id='0224928385b6426ab236fc8492137a94')
retrieved_ref

```

Out[85]:
[{'creation_time': '2016-06-23T19:24:46',
  'description': u'this is a cloned ref',
  'enabled': True,
  'head_id': u'a1c5a5dbec8d47e9b22afd674e43942b',
  'last_modified': '2016-06-23T19:24:46',
  'lcms_run': None,
  'name': u'Untitled',
  'prev_uid': u'4af432747f06463aa58143eb3850d913',
  'ref_type': u'',
  'rt_max': 7.06,
  'rt_min': 6.39708032852564,
  'rt_peak': 6.96,
  'rt_units': 'min',
  'unique_id': u'0224928385b6426ab236fc8492137a94',
  'username': u'bpb'}]

**Comment by blink1073** [comment]
Cloning always sets the user to the current one, I think that is what you're seeing.
