### ISSUE TITLE
Correct way to serialize datestamps in metatlas objects?

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#143]
I'm adding the acquisition time to the metatlas objects, and am doing something wrong serializing the time stamps.  Can you point me in the right direction?

If I understand your implementation, you save utc_timestamps as integers, but when retrieved, they are shown as date strings.  I've got the saving of utc_timestamps:
https://github.com/biorack/metatlas/blob/master/metatlas/directory_watcher.py#L146

but it would be nice if mine serialized the same way as yours.

```
f = metob.retrieve('Lcmsrun',mzml_file = '%20160725_SK_TEST1_upload%',username = '*')
[{'acquisition_time': 1468473034,
  'creation_time': '2016-07-25T20:56:46',
  'description': u'20160725_SK_TEST1_upload TESTUPLOADFILE_SK_QC_POS_QE144.mzML',
....]
```

**Comment by blink1073** [comment]
Is this what you're looking for?  https://github.com/biorack/metatlas/blob/master/metatlas/object_helpers.py#L506

**Comment by benbowen** [comment]
Nope, I found that already. Hidden treasures of pandas....  What I'm trying
to figure out is when I retrieve an object with a time attribute, it is a
timestamp, but when I print an object, the time attributes show as time
string.  How do i make my new attribute Acquisition_time behave the same
way?

**Comment by blink1073** [comment]
https://github.com/biorack/metatlas/blob/master/metatlas/metatlas_objects.py#L236

**Comment by benbowen** [comment]
Got it.  I think I'll leave acquisition_time as an integer timestamp so as not to have precarious condition statements in __repr__ for metatlas objects.  

I also noticed that load_lcms_runs in metatlas_objects:
https://github.com/biorack/metatlas/blob/master/metatlas/metatlas_objects.py#L310

needs to be consistent with update_metatlas in directory_watcher.py:
https://github.com/biorack/metatlas/blob/master/metatlas/directory_watcher.py#L60

Thanks!
