### ISSUE TITLE
Add Scan Parameters Information

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#32]
Currently, we would have to dive into the mzML file to get the metadata about a scan.  Its in the header of the xml file.  Not all vendors store the information in the same format.

Nevertheless, we need a minimal but sufficient specification to store this.  Around 10K scans per file.  
One way is here:
https://www.draw.io/#G0BweRoDuGcsLBOGVvUlFneUNGdDg

**Comment by blink1073** [comment]
You want to store 10K of these objects per file?

**Comment by benbowen** [comment]
I'm not sure of a good way to handle it.  Is there a github label for tickets that are put in a parking lot.  We need to address this, but not sure now is best itme.

**Comment by blink1073** [comment]
Fair enough, deferring.

**Comment by benbowen** [comment]
One way, would be to write a function that gets information directly from the original mzML file.  Typically, we are going to want collision energy for a particular scan.

For situations where tandem-mass spectrometry is acquired using two different machines (one scan is taken on instrument_1 and the next scan is taken on insturment_2) you would want to know more.

The later is less common, but still exists.  We have a machine like that.

**Comment by blink1073** [comment]
We could store it as another table in the HDF5 file.

**Comment by benbowen** [comment]
Could we store as text?  Often the metadata about the scan isn't structured
using the ontology keys.

On Fri, Oct 30, 2015 at 12:44 PM, Steven Silvester <notifications@github.com

**Comment by blink1073** [comment]
Yep, you can use `StringCol(256)`, or some large buffer size.

**Comment by blink1073** [comment]
What if we organized the HDF file as such:

```python
class SpectrumData(tables.IsDescription):
    mz = tables.Float32Col(pos=0)
    i = tables.Float32Col(pos=1)
    scan = tables.Int32Col(pos=2)


class ScanParams(tables.IsDescription):
    rt = tables.Float32Col(pos=0)
    mz_range = tables.Float32Col(pos=0)
    instrument = tables.StringCol(256, pos=1)
    ion_source = tables.StringCol(256, pos=2)
    mass_analyzer = tables.StringCol(256, pos=3)
    polarity = tables.EnumCol(pos=4)
    scan_duration = tables.Float32Col(pos=5)


class MS2Params(ScanParams):
    precursor_MZ = tables.Float32Col(pos=6)
    precursor_intensity = tables.Float32Col(pos=7)
    collision_energy = tables.Float32Col(pos=8)
    fragmentation_type = tables.StringCol(256, pos=9)
```

**Comment by benbowen** [comment]
Also, add ChromatogramData():
    mz ....
    i ....
    scan ....

ChromatogramData would be lined up for a logically reduced set of mz values
to allow rapid slicing in the time dimension.  Currently, slicing is fast
for spectra and much slower for time.

**Comment by benbowen** [comment]
GetData and GetSpectrum would operate on SpectrumData, but GetChromatogram
would operate on ChroamtogramData.

Perhaps the MSMS queries confound this, but it seems possible that for pos,
neg, MS1, and MS2 layers, there could be both a spectrumdata and a
chromatogram data.  The file api would use the correct logic to request
data.

**Comment by benbowen** [comment]
That sounds like a significant improvement over what we currently have.  I'm worried about optimizing the speed of slicing operations, but data without metadata is nothing.  I made a new ticket about storing two layouts of the [mz, intensity] data.  One for spectra and one for time.
