### ISSUE TITLE
Need a GUI for getting data from an Atlas for an Experiment (group of groups)

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#50]
Here's a programmatic example:
http://nbviewer.ipython.org/url/portal.nersc.gov/project/openmsi/MetAtlas_005_Find_Data_in_Grouped_Files_For_Given_Atlas.ipynb?flush_cache=true

**Comment by aitatanit** [comment]
I am having issues running this code on my computer. I will try to run it on NERSC before we chat this afternoon.

**Comment by benbowen** [comment]
There is a lot of old stuff in that code that needs to be updated to the
most recent syntax.  I can update it and repost if you need.

Big things are:
1) order of execution on the imports.  The metob path and import need to be
first
2) username = '*' on the retrieve commands
3) camelcase vs underscore.  Steve did a bunch of pep8 stuff in december.

**Comment by aitatanit** [comment]
Yes I tried updating a few things but I am stuck on one sore spot. I'll
discuss later ...


--
*Jimmy*

**Comment by benbowen** [comment]
Here is more updated version
