### ISSUE TITLE
Optimize Get Chromatogram queries

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#55]
Because the data is layed out in spectra, queries for slicing out of chromatograms are slower.

To the HDF5 file, we could add ChromatogramData():
    mz ....
    i ....
    scan ....

ChromatogramData would be lined up for a logically reduced set of mz values
to allow rapid slicing in the time dimension.  Currently, slicing is fast
for spectra and much slower for time.

The reduced m/z could come from peakdet or some simple clustering to O:1M m/z bins.

GetData and GetSpectrum would operate on SpectrumData, but GetChromatogram
would operate on ChroamtogramData.

Perhaps the MSMS queries confound this, but it seems possible that for pos,
neg, MS1, and MS2 layers, there could be both a spectrumdata and a
chromatogram data.  The file api would use the correct logic to request
data.

Adding compression would be essential here.  Storing all those zeros would blow up the file.  We do something similar in OpenMSI with a compression and chunking operation at the file level.

**Comment by blink1073** [comment]
Bottom line: the only real way to get faster searches is by having one table sorted by scan (the default), and a second one ordered by `m/z`.  I tried:

- Creating a completely sorted index for `m/z`
- Sorting the individual spectra by `m/z`
- Different levels of compression (and no compression)
- Sorting by `m/z` and using an integer for spectrum number

This means our files will be twice the size, but chromatogram searches will be much faster.  For a 16MB mzML, I got an 18MB HDF.

We store the data as follows:

```python
class SpectrumData(tables.IsDescription):
    mz = tables.Float32Col(pos=0)
    i = tables.Float32Col(pos=2)
    scan = tables.Int32Col(pos=3)

class ScanParams(tables.IsDescription):
    rt = tables.Float32Col(pos=0)
    polarity = tables.BoolCol(pos=1)
    scan_duration = tables.Float32Col(pos=2)
    mz_range = tables.Float32Col(pos=3)
    instrument = tables.StringCol(256, pos=4)
    ion_source = tables.StringCol(256, pos=5)
    mass_analyzer = tables.StringCol(256, pos=6)
    # the rest are only relevant for ms2 spectra
    precursor_MZ = tables.Float32Col(pos=7)  
    precursor_intensity = tables.Float32Col(pos=8)
    collision_energy = tables.Float32Col(pos=9)
    fragmentation_type = tables.StringCol(256, pos=10)
```

We query the scan parameter tables to get the relevant scan indices, then use the `m/z` table if there is `m/z` in the search criteria and the `rt` table otherwise.

**Comment by blink1073** [comment]
Note: this requires modifying the `directory_watcher` temporarily to not create an entry in the LCMSRuns table if one already exists, then removing all of the existing H5 files and letting the CRON job create the new ones.

**Comment by blink1073** [comment]
Implemented in 04b36d6b1d6a7f48d05dbf66a713234693884a5d, now testing.

**Comment by blink1073** [comment]
@benbowen, I verified that it is working, I deleted your h5 files first so they'll be ready for tomorrow.

**Comment by blink1073** [comment]
Note the signature change for the functions in `h5_query`, they now take `ms_level` and `polarity` as keyword arguments instead of positional ones, because I've added some intelligence to find the appropriate polarity and ms_level for a given file.

**Comment by benbowen** [comment]
I'm worried that for MSMS data something is being lost.  Here is the
request and return for an old file:
In [53]:

myfiles
with tables.open_file(myfiles[0]) as fid:
    data = h5q.get_data(fid,ms_level=2,polarity=1,min_rt = 1.0)
data
Out[53]:
array([ (51.652156829833984, 1.0039352178573608, 5010.71240234375,
158.9600067138672, 7554785.0, 20.0),
       (55.93556213378906, 1.0039352178573608, 263510.3125,
158.9600067138672, 7554785.0, 20.0),
       (55.94639587402344, 1.0039352178573608, 5741.85498046875,
158.9600067138672, 7554785.0, 20.0),
       ...,
       (152.10720825195312, 11.504484176635742, 6393.5810546875,
149.94000244140625, 2308425.75, 20.0),
       (167.95175170898438, 11.504484176635742, 10828.421875,
149.94000244140625, 2308425.75, 20.0),
       (169.9484100341797, 11.504484176635742, 3158.89453125,
149.94000244140625, 2308425.75, 20.0)],
      dtype=[('mz', '<f4'), ('rt', '<f4'), ('i', '<f4'), ('precursor_MZ',
'<f4'), ('precursor_intensity', '<f4'), ('collision_energy', '<f4')])


Here is the request and return for a new file:

   with tables.open_file(r) as fid:
        data = h5q.get_data(fid,ms_level=2,polarity=1,min_rt = 1.0)

array([(56.51008987426758, 1378.845703125, 1.00601065158844),
       (58.498207092285156, 1307.128662109375, 1.00601065158844),
       (60.39899826049805, 1240.85791015625, 1.00601065158844), ...,
       (143.9564208984375, 1854.0528564453125, 43.00236511230469),
       (259.23175048828125, 1987.5975341796875, 43.00236511230469),
       (287.00830078125, 2001.9381103515625, 43.00236511230469)],
      dtype=[('mz', '<f4'), ('i', '<f4'), ('rt', '<f4')])

**Comment by blink1073** [comment]
Which file is that?

**Comment by benbowen** [comment]
old:

u'/project/projectdirs/metatlas/raw_data/lpsilva/20150521_LPSilva_Actino_C18_NEG_51isolates/20150514_C18_NEG_MSMS_D1B20A-1.h5'

new:

u'/project/projectdirs/metatlas/raw_data/lpsilva/20150514_LPSilva_Actino_C18_POS_51isolates/20150510_C18_POS_MSMS_D1B20A-1.h5'


On Wed, Dec 23, 2015 at 12:54 PM, Steven Silvester <notifications@github.com

**Comment by benbowen** [comment]
hang on. I'll resend in a second.  disregard last email.

**Comment by blink1073** [comment]
I got the data using scp.

**Comment by blink1073** [comment]
Ah, your concern is that it no longer returns the other data types.  I'll fix that.

**Comment by blink1073** [comment]
Argh, there was no clean way to recreate this information, I had to bump the hdf file format version and restart the conversions.

**Comment by blink1073** [comment]
I've caught up to where I was before with the new version, humming along with two CRON jobs.

**Comment by benbowen** [comment]
We are qualified for the realtime queue up to 32 nodes.  I just tested it
yesterday.  We should do a test for rebuilding the files this way
sometime.  It's quite spectacular.  36 threads per node and 32 nodes is a
pretty big multiplier.

**Comment by benbowen** [comment]
Done using numexpr and pandas hdf5 tools.  10x faster.
