### ISSUE TITLE
Make an RT Corrector and Compound Viewer App

### ISSUE THREAD

**Issue by blink1073** [biorack/metatlas#64]
Below is the one from MetAtlas 1.0 and it ran in matplotlib outside of the browser.  Seems like making something like this would touch all the moving parts of MetAtlas 2.0.

![image](https://cloud.githubusercontent.com/assets/2096628/11260862/c4c6fd0e-8e34-11e5-8c36-46e981781bc1.png)

You can click through all the compounds in an Atlas and adjust the retention times for that compound by sliding the blue and red vertical boxes.

**Comment by benbowen** [comment]
Here is the code for the matplotlib screenshot.  Its my first interactive python plot; so sorry for the spaghetti.

def updateAtlas(compoundData,client):
    b = {'rt_min':compoundData['rt_min'],'rt_max':compoundData['rt_max'],'rt_peak':compoundData['rt_peak']}
    url = 'https://metatlas.nersc.gov/api/compound/%s/' % compoundData[u'_id']
    r = client.patch(url, data=json.dumps(b))
    print r.text

class IndexTracker:
    def __init__(self, fig,ax,compoundIdx,dictData,data,export_fileIds,filenames,fileGroups,client):
        self.figure = fig
        self.client = client
        self.ax = ax
        self.rectangleWidth = 0.03 #the width of the rectangle patches
        self.compoundIdx = compoundIdx
        self.dictData = dictData
        self.data = data
        self.export_fileIds = export_fileIds
        self.plotHandles = []
        self.filenames = filenames
        self.filegroups = fileGroups
        self.numPlots = len(filenames)
        self.fileIdx = 0
        self.initPlots()
        self.update()
        self.axprev = plt.axes([0.1, 0.02, 0.15, 0.08])
        self.axnext = plt.axes([0.75, 0.02, 0.15, 0.08])
#         self.axupdate = plt.axes([0.45, 0.02, 0.15, 0.08])
        self.bnext = Button(self.axnext, 'Next\nCompound')
        self.bprev = Button(self.axprev, 'Previous\nCompound')
#         self.bupdate = Button(self.axupdate, 'Update\nAtlas')
        self.bnext.on_clicked(self.next)
        self.bprev.on_clicked(self.prev)
#         self.bupdate.on_clicked(self.updateAtlas)
        self.axprevRun = plt.axes([0.1, 0.82, 0.15, 0.08])
        self.axnextRun = plt.axes([0.75, 0.82, 0.15, 0.08])
        self.bnextRun = Button(self.axnextRun, 'Next\nRun')
        self.bprevRun = Button(self.axprevRun, 'Previous\nRun')
        self.bnextRun.on_clicked(self.nextRun)
        self.bprevRun.on_clicked(self.prevRun)
#         self.radio_ax = plt.axes([0.13, 0.67, 0.2, 0.15])
#         self.radio = RadioButtons(self.radio_ax, ('Experiment','Run'))
#         self.radio_ax.set_axis_off()
#         self.radio.on_clicked(self.run_or_experiment)
#         self.timeevent = int(round(time.time() * 1000))
        
#         self.radio_range_ax = plt.axes([0.73, 0.67, 0.2, 0.15])
#         self.radio_range = RadioButtons(self.radio_range_ax, ('Max of Data','Max in Range'))
#         self.radio_range_ax.set_axis_off()
#         self.radio_range.on_clicked(self.run_or_experiment)

        
#         rax = plt.axes([0.05, 0.4, 0.1, 0.15])
# check = CheckButtons(rax, ('2 Hz', '4 Hz', '6 Hz'), (False, True, True))

# def func(label):
#     if label == '2 Hz': l0.set_visible(not l0.get_visible())
#     elif label == '4 Hz': l1.set_visible(not l1.get_visible())
#     elif label == '6 Hz': l2.set_visible(not l2.get_visible())
#     plt.draw()
# check.on_clicked(func)

        
#     def run_or_experiment(self, label):
#     # this determines if the edit is supposed to be run level or experiment level
#         self.levelEdit = label
    
    def initPlots(self):
        self.plotHandles = []
        minX = 1e6
        maxX = 0
        maxY = 0
        if len(self.data[self.compoundIdx])>3:
            for j,myFile in enumerate(self.export_fileIds):
                x1 = data[self.compoundIdx][:,0][(data[self.compoundIdx][:,2]==myFile)]
                y1 = data[self.compoundIdx][:,1][(data[self.compoundIdx][:,2]==myFile)]
                idx = np.argsort(x1)
                x1 = x1[idx]
                y1 = y1[idx]
                if len(x1)>0:
                    if max(x1) > maxX:
                        maxX = max(x1)
                    if min(x1) < minX:
                        minX = min(x1)
                    if max(y1) > maxY:
                        maxY = max(y1)
                    h = self.ax.plot(x1,y1,'k-',linewidth=2.0,alpha=0.1)
                    self.plotHandles.append(h)

            rect1 = Rectangle((float(self.dictData[u'compounds'][self.compoundIdx][u'rt_min']) - self.rectangleWidth/2,0), 0.03, maxY*1.025, color='blue', alpha=0.5,)
            rect2 = Rectangle((float(self.dictData[u'compounds'][self.compoundIdx][u'rt_max']) - self.rectangleWidth/2,0), 0.03, maxY*1.025, color='blue', alpha=0.5,)
            rect3 = Rectangle((float(self.dictData[u'compounds'][self.compoundIdx][u'rt_peak']) - self.rectangleWidth/2,0), 0.03, maxY*1.025, color='red', alpha=0.5,)

            self.ax.rect1 = self.ax.add_patch(rect1)
            self.ax.rect2 = self.ax.add_patch(rect2)
            self.ax.rect3 = self.ax.add_patch(rect3)
            self.ax.rtMin_line = self.ax.axvline(float(self.dictData[u'compounds'][self.compoundIdx][u'rt_min']),color='blue',linewidth=2.0)
            self.ax.rtMax_line = self.ax.axvline(float(self.dictData[u'compounds'][self.compoundIdx][u'rt_max']),color='blue',linewidth=2.0)
            self.ax.rtPeak_line = self.ax.axvline(float(self.dictData[u'compounds'][self.compoundIdx][u'rt_peak']),color='red',linewidth=2.0)

#             self.ax.rect1.connect()
            self.drs = []
            dr = self.DraggableRectangle(self.ax.rect1)
            dr.connect()
            self.drs.append(dr)
            dr = self.DraggableRectangle(self.ax.rect2)
            dr.connect()
            self.drs.append(dr)
            dr = self.DraggableRectangle(self.ax.rect3)
            dr.connect()
            self.drs.append(dr)
            
            if float(self.dictData[u'compounds'][self.compoundIdx][u'rt_max']) > maxX:
                maxX = float(self.dictData[u'compounds'][self.compoundIdx][u'rt_max'])*1.025
            
            if float(self.dictData[u'compounds'][self.compoundIdx][u'rt_min']) < minX:
                minX = float(self.dictData[u'compounds'][self.compoundIdx][u'rt_min'])*0.975
                
            self.ax.set_xlim(minX,maxX)
            self.ax.set_ylim(0,maxY*1.025)


        
    def nextRun(self,event):
        self.fileIdx = np.clip(self.fileIdx+1, 0, self.numPlots-1)
        self.update()

    def prevRun(self,event):
        self.fileIdx = np.clip(self.fileIdx-1, 0, self.numPlots-1)
        self.update()
        
    def onscroll(self,event):
        if event.button=='up':
            self.nextRun(self)
        else:
            self.prevRun(self)
    
    def update(self):
        self.ax.set_title('Compound: %s\nFile #%d %s\n%s' % (self.dictData[u'compounds'][self.compoundIdx][u'name'], self.fileIdx, self.filenames[self.fileIdx], self.filegroups[self.fileIdx]) )
        for h in self.plotHandles:
            h[0].set_alpha(0.1)
        if len(self.plotHandles) > 0:
            self.plotHandles[self.fileIdx][0].set_alpha(1)
        self.figure.canvas.draw()
#         self.figure.savefig('bad_rt.pdf')
    
    def next(self, event):
        self.compoundIdx = np.clip(self.compoundIdx+1, 0, len(self.data)-1)
        self.ax.lines = []
        if len(self.plotHandles) > 0:
            self.ax.rect1.remove()
            self.ax.rect2.remove()
            self.ax.rect3.remove()
        self.initPlots()
        self.update()

    def prev(self, event):
        self.compoundIdx = np.clip(self.compoundIdx-1, 0, len(self.data)-1)
        self.ax.lines = []
        if len(self.plotHandles) > 0:
            self.ax.rect1.remove()
            self.ax.rect2.remove()
            self.ax.rect3.remove()
        self.initPlots()
        self.update()

    class DraggableRectangle:
        def __init__(self, rect):
            self.rect = rect
            self.press = None

        def connect(self):
            'connect to all the events we need'
            self.cidpress = self.rect.figure.canvas.mpl_connect(
                'button_press_event', self.on_press)
            self.cidrelease = self.rect.figure.canvas.mpl_connect(
                'button_release_event', self.on_release)
            self.cidmotion = self.rect.figure.canvas.mpl_connect(
                'motion_notify_event', self.on_motion)

        def on_press(self, event):
            'on button press we will see if the mouse is over us and store some data'
            if event.inaxes != self.rect.axes: return
            contains, attrd = self.rect.contains(event)
            if not contains: return
#             print 'event contains', self.rect.xy
            x0, y0 = self.rect.xy
            self.press = x0, y0, event.xdata, event.ydata


        def on_motion(self, event):
            'on motion we will move the rect if the mouse is over us'
            if self.press is None: return
            if event.inaxes != self.rect.axes: return
            x0, y0, xpress, ypress = self.press
            dx = event.xdata - xpress
#             dy = event.ydata - ypress
            #print 'x0=%f, xpress=%f, event.xdata=%f, dx=%f, x0+dx=%f'%(x0, xpress, event.xdata, dx, x0+dx)
            self.rect.set_x(x0+dx)
#             self.rect.set_y(y0)
            
            self.rect.figure.canvas.draw()


        def on_release(self, event):
            self.press = None
            self.rect.figure.canvas.draw()
            myTracker.figure.canvas.draw()
            
            myTracker.dictData[u'compounds'][myTracker.compoundIdx][u'rt_min'] = unicode( myTracker.ax.rect1.get_x() + myTracker.rectangleWidth/2 )
            myTracker.dictData[u'compounds'][myTracker.compoundIdx][u'rt_max'] = unicode( myTracker.ax.rect2.get_x() + myTracker.rectangleWidth/2 )
            myTracker.dictData[u'compounds'][myTracker.compoundIdx][u'rt_peak'] = unicode( myTracker.ax.rect3.get_x() + myTracker.rectangleWidth/2 )

            myTracker.ax.rtMin_line.set_xdata(myTracker.ax.rect1.get_x() + myTracker.rectangleWidth/2)
            myTracker.ax.rtMax_line.set_xdata(myTracker.ax.rect2.get_x() + myTracker.rectangleWidth/2)
            myTracker.ax.rtPeak_line.set_xdata(myTracker.ax.rect3.get_x() + myTracker.rectangleWidth/2)

            updateAtlas(myTracker.dictData[u'compounds'][myTracker.compoundIdx],myTracker.client)
            

        def disconnect(self):
            'disconnect all the stored connection ids'
            self.rect.figure.canvas.mpl_disconnect(self.cidpress)
            self.rect.figure.canvas.mpl_disconnect(self.cidrelease)
            self.rect.figure.canvas.mpl_disconnect(self.cidmotion)

        
fig = plt.figure()
fig.set_facecolor('white')
ax = fig.add_subplot(111)
plt.subplots_adjust(bottom=0.2, top=0.8)


filenames = []
fileGroups = []
for i,myFile in enumerate(export_fileIds):
    for j,fid in enumerate(fileInfo['fid']):
        if fid == myFile:
            filenames.append(fileInfo['name'][j])
            fileGroups.append(fileInfo['group'][j])

compoundIdx=0


ax.set_xlabel('Time (min)',weight='bold')
ax.set_ylabel('Magnitude (au)',weight='bold')

# axcolor = 'green'


myTracker = IndexTracker(fig,ax,compoundIdx,dictData,data,export_fileIds,filenames,fileGroups,client)
fig.canvas.mpl_connect('scroll_event', myTracker.onscroll)

plt.show()
# plot_url = py.plot_mpl(fig)

**Comment by benbowen** [comment]
@aitatanit Its probably pretty clear, but the example code above is for the old SciDB database and Django API.  In that workflow, chromatograms were pre-fetched for all compounds and all files.  The matplotlib tool let you adjust the retention time specifications in your Atlas in the context of this data.

We can go this way for the new app or we can fetch the data on the fly.  The way thigns are currently, On the fly will be too slow if there are more than 10 files or so.  See tickets #55 and #82.

**Comment by benbowen** [comment]
@aitatanit is working on this and showed me a demo today.  Has a nice prototype with sliders and interactive tooltips.

**Comment by benbowen** [comment]
I'm taking this task over.  There is an inconsistency for the nersc environment vs @aitatanit's environment.  So far fixed:
1) Made workign notebook in docs/example_notebooks
2) Made pickle file selector that works at NERSC
3) Moved the qgrid into the same code cell at matplotlib and widgets
4) Numerous typos

Big todo: Currently, compounds are matched between Atlas and pickle by compound.name.  This doesn't work because often there are multiple identifications for the same compound (adducts and uncertain isomers or elution times). Will fix by using unique ids from the compound entry in the pickle and the atlas.

**Comment by benbowen** [comment]
Done
