### ISSUE TITLE
Targeted_hybrid notebook: atlas_df not generated when loading from csv 

### ISSUE THREAD

**Issue by tharwood3** [biorack/metatlas#663]
After running section 5b "Load atlas from CSV file" in the Targeted-hybrid notebook there is no way to generate the atlas_df object without redefining csv_atlas_file_name as None. It would probably be better to streamline this section so that the user doesn't need to manually redefine any of the initial parameters.

**Comment by wholtz** [comment]
in #699, `atlas_df` will alway get generated if you run all code blocks, independent of the value in `csv_atlas_file_name`.
