### ISSUE TITLE
Targeted_hybrid notebook: AnalysisIdentifiers() not working in current version

### ISSUE THREAD

**Issue by tharwood3** [biorack/metatlas#664]
The "ids = AnalysisIdentifiers()" block in section 7 of the Targeted_hybrid errors out in the current version. 

```
2022-08-04 23:00:18 CRITICAL Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_64481/2964584432.py", line 1, in <cell line: 1>
    ids = AnalysisIdentifiers(project_directory, experiment, output_type, polarity, analysis_number, google_folder,
TypeError: __init__() got an unexpected keyword argument 'source_atlas'
```

**Comment by wholtz** [comment]
`Targeted_hybrid.ipynb` has not yet been updated for the v3.x of Metatlas (config file support). Until that happens, you'll need to set the parameter `source_code_version_id = "v2.6.0"`. 

I'll update this issue when the notebook has been updated to run on the current code.

**Comment by wholtz** [comment]
The current main branch and the Targeted_hybrid.ipynb committed within in should be functional together.
