### ISSUE TITLE
Need a suitable place for my helper functions

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#77]
I'm ready to put some of my helper functions into the metatlas repo.  Where should I put them?

They can broadly be broken into the following 4 categories:
1) Plotting
2) Dataframe creation
3) Pactolus & MetAtlas Integration Helpers
4) Getting data from hdf5 and/or doing things to data after slicing from hdf5
5) Database helpers

**Comment by blink1073** [comment]
1) There is now a `plotting.py`.
4) `h5_query.py`
5) `metatlas_objects.py`

I'd say make new files for 2) and 3), perhaps `dataframes.py` and `integration.py`.

**Comment by benbowen** [comment]
Sorry for taking so long.  I'm almost ready.  Still making tons of tweaks.

**Comment by benbowen** [comment]
This is done.  I have put most code in helpers for now.
