### ISSUE TITLE
Update metatlas source code & DB to be NERSC-agnostic

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#81]
Make it easy to run the metatlas code on a local computer, so that developers may directly use local tools & text editors, pull the production database & some data files locally for analysis, etc.

Currently, the source code & database have hard-coded dependencies on NERSC.  Update the code & DB so that metatlas will run on both system, without any code changes.

We did this for OpenMSI in a simple way.  The basic idea is a "local_settings.py" file that is NOT checked into the repo, and we add many examples of "local_settings_<device_name>.py" and put those into the repo.  You can even commit your own; as long as it isn't called "local_settings.py".  Typically, a user selects the one most similar to their needs and renames it "local_settings.py" and it sets up all the environment variables, paths, etc.  We have "local_settings_nersc.py", "local_settings_mac_laptop.py", etc. checked into the repo.

The OpenMSI local_settings is mostly django stuff.

**Comment by blink1073** [comment]
It works on a local machine as is (it works on Travis).  You just have to use `load_lcms_files` on a local machine to get the files loaded.  To move it to a different system, you'd have to update the database path on `object_helpers.py`, use the same   `raw_data/username/experiment/file.mzml` layout, and update `scripts/run_dirwatch2.sh`, and update and install `scripts/crontab.corigrid.pasteur`.

**Comment by aitatanit** [comment]
This should have been closed a while back. I am running everything locally and it works all well. However, any mods to the DB are not reflected on NERSC. Maybe we need to find a way to sync DBs. 
Will open another issue to solve this
