### ISSUE TITLE
Regular backups of meta_atlas MySQL DB on NERSC

### ISSUE THREAD

**Issue by mkopala** [biorack/metatlas#86]
There needs to be regular DB dumps of the `meta_atlas` DB for backup purposes, in case the database gets corrupted, data gets deleted accidentally, etc.

This probably makes most sense as a cron job run by the `pasteur` user.

**Comment by mkopala** [comment]
@metabolite-atlas/owners One of you guys will have to do this, I guess.

**Comment by benbowen** [comment]
Snapshots are taken by NERSC automatically, but we need to get the specifications from them and go through a practice recovery.
