### ISSUE TITLE
add reference_intensity as an identification

### ISSUE THREAD

**Issue by benbowen** [biorack/metatlas#98]
see https://www.draw.io/#G0BweRoDuGcsLBOGVvUlFneUNGdDg

peak_area, peak_height, and amount will be floats
amount_units will be str

Steve used a python database manager to help ease the create of new objects and tables.  I don't know how he handles database migration when new types are added

**Comment by blink1073** [comment]
Making a new table means adding a new class to `metatlas_objects.py`.  Floats are set as single precision by default, unfortunately, so here is the best way to create a table (probably should be added to the admin docs).

Create a new table
--------------------------
1) Create a new class in `metatlas_objects.py`.
2) Create a new object of that class and `store` it.
3) Log into database
4) Run `alter table TABLE_NAME modify COLUMN_NAME double;` for each float column

Add a floating point object to a new table
1) Update the class in `metatlas_objects.py`.
2) Create an object with the updated class and `store` it.
3) Log into database
4) Run `alter table TABLE_NAME modify COLUMN_NAME double;` for each new float column

**Comment by blink1073** [comment]
Steps 2-4 could probably be added as a utility method (like `update_table(table_klass)`) in `object_helpers.py`.

**Comment by aitatanit** [comment]
Shouldn't be complicated!
I'm using a local version of the mysql DB so I can play with it and debug it without affecting the nersc db

**Comment by aitatanit** [comment]
What units do you want to use?

**Comment by benbowen** [comment]
Free text string for now

**Comment by blink1073** [comment]
I forgot I had already added a `fix_table` function in `Workspace` that is called when the table is created, ha!

**Comment by benbowen** [comment]
This seems synergistic with issue #103

**Comment by benbowen** [comment]
Done. Added Intensity Reference Object.  Will be visible on next commit.
